# Generated by Django 4.2.16 on 2024-10-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_account', models.CharField(blank=True, max_length=400, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_brgy', to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respondent_gender', to='management.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField(blank=True, null=True)),
                ('question_2', models.TextField(blank=True, null=True)),
                ('question_3', models.TextField(blank=True, null=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_respondent', to='management.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_question', to='management.questionquestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_questionnaire_question', to='management.questionquestionnaire')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_respondent', to='management.respondent')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_question_option', to='management.questionoptions')),
            ],
        ),
    ]
