# Generated by Django 4.2.16 on 2024-10-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_gender_questionquestionnaire_respondent_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='management.questionoptions'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_question_option', to='management.questionoptions'),
        ),
    ]
