# Generated by Django 4.2.16 on 2024-10-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_questionnaire_selected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
