# Generated by Django 4.2.16 on 2024-10-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_questionoptions_counts_questionoptions_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BrgyLeaderAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brgy_leader_attendance', to='management.barangay')),
                ('individuals', models.ManyToManyField(blank=True, to='management.respondent')),
                ('time_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.timemark')),
            ],
        ),
    ]
